# Generated by Django 3.0.8 on 2020-08-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='name',
            field=models.CharField(help_text='Maximum length is 255 symbols', max_length=255, unique=True, verbose_name='Pair name'),
        ),
    ]
