version: '2'
services:
  'db':
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    env_file: .envs/db.env
    volumes:
      - ./db-data:/var/lib/postgresql/data

  'app':
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .envs/app.env
      - .envs/db.env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - celery
    ports:
      - 8000:8000
    restart: on-failure:10

  'redis':
    image: redis

  'celery':
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .envs/app.env
      - .envs/db.env
    command: celery worker -A demigos.taskapp -l INFO
    depends_on:
      - redis

  'celerybeat':
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .envs/app.env
      - .envs/db.env
    command: bash -c "rm -f './celerybeat.pid' && celery beat -A demigos.taskapp -l INFO"
    depends_on:
      - redis
